services:
  api_gestao:
    build: .
    container_name: gestao_api_dev
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db_gestao
    networks:
      - internal_net
      - kong-network
      - kafka-net

  db_gestao:
    image: postgres:15
    container_name: ${DB_HOST}
    ports:
      - "4000:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal_net
      - kafka-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c wal_level=logical -c max_wal_senders=10 -c max_replication_slots=10


volumes:
  pgdata:

networks:
  internal_net:
    driver: bridge
  kong-network:
    external: true
  kafka-net:
    external: true
    name: empregados-plansul-network
